---

# For use with pre-commit.
# See usage instructions at https://pre-commit.com

-   id: bashate
    name: bashate
    description: This hook runs bashate for linting shell scripts
    entry: bashate
    language: python
    types: [shell]
